CREATE TABLE IF NOT EXISTS users (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	firstname VARCHAR(30) NOT NULL,
	lastname VARCHAR(30) NOT NULL,
	age INT(3) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS auths (
    email VARCHAR(50) PRIMARY KEY,
    pwd VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    user_id INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
-- CREATE TABLE IF NOT EXISTS reviews (
-- 	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
-- 	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     author_id INT(6) NOT NULL,
--     product_id VARCHAR(255) NOT NULL,
--     rate TINYINT DEFAULT NULL,
--     comment VARCHAR(255) DEFAULT NULL
-- );

-- COPY PatientInfo FROM '/home/data/PatientInfo.csv' DELIMITER ',' CSV HEADER;
-- COPY Datasource FROM '/home/data/datasource.csv' DELIMITER ',' CSV HEADER;
-- COPY province FROM '/home/data/province.csv' DELIMITER ',' CSV HEADER;